version: '2'

services:
  homebridge:
    build:
      context: .
      # Uncomment below to use the Raspberry Pi build
      # dockerfile: Dockerfile-rpi
    restart: always
    network_mode: host
    volumes:
      - ./.homebridge:/root/.homebridge
      - ./bin:/root/code/bin
    logging:
      options:
        max-size: 1m
        max-file: '10'
