version: '2'

services:
  data:
    build: .
    restart: always
    network_mode: host
    volumes:
      - ./.homebridge/accessories:/root/.homebridge/accessories
      - ./.homebridge/persist:/root/.homebridge/persist
