FROM hypriot/rpi-node:6.5.0

RUN apt-get update && \
    apt-get install -y avahi-daemon libavahi-compat-libdnssd-dev && \
    mkdir -p /var/run/dbus && \
    sed -i \
      -e 's/#enable-dbus=yes/enable-dbus=yes/' \
      -e 's/rlimit-nproc=3/#rlimit-nproc=3/' \
      /etc/avahi/avahi-daemon.conf

WORKDIR /code

COPY bin/npm-install-with-retry /code/bin/npm-install-with-retry
COPY package.json /code/package.json
RUN bin/npm-install-with-retry

COPY bin/init /code/bin/init
COPY config.json /root/.homebridge/config.json

CMD ["/code/bin/init"]
