FROM hypriot/rpi-node:6.5.0

RUN apt-get update && \
    apt-get install -y avahi-daemon libavahi-compat-libdnssd-dev && \
    mkdir -p /var/run/dbus && \
    sed -i 's/#enable-dbus=yes/enable-dbus=yes/' /etc/avahi/avahi-daemon.conf

WORKDIR /code

# XXX: The tarball for mdns@2.3.3 is corrupted, so manually install 2.3.2
# instead. Self note: check this later to see if mdn > 2.3.3 has this issue.
RUN npm install mdns@2.3.2

COPY package.json /code/package.json
RUN npm install

COPY bin/init /code/bin/init
COPY config.json /root/.homebridge/config.json

CMD ["/code/bin/init"]
